const express=require('express');
const cors=require('cors');
const mongoose=require('mongoose');
const dotenv=require('dotenv');
dotenv.config();
const app=express();
app.use(cors());
app.use(express.json());
mongoose.connect(process.env.MONGO_URI).then(()=>console.log('Mongo Connected'));
app.get('/',(req,res)=>res.send('Smart HomeCare Backend Running'));
app.listen(process.env.PORT||5000);